name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Tools & Cache
        uses: ./.github/actions/setup

      # Cache the installed node_modules directory
      - name: Cache node_modules
        uses: actions/cache@v4
        id: node_modules_cache_id
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('pnpm-lock.yaml') }}

      # If the cache didn't exist, run pnpm install
      - name: Install dependencies
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: pnpm install
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Restore node_modules from cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Create .env file
        run: |
          echo "ORIGIN=https://skyblockrepo.com" > .env
          echo "PUBLIC_HOST_URL=https://skyblockrepo.com" >> .env
          echo "PUBLIC_COMMIT_HASH=${GITHUB_SHA::7}" >> .env

      - name: Build
        run: pnpm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
